<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_CallForPrice
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Model\Product;
use Magento\Framework\App\ActionInterface;

/** @var $block \Magento\Catalog\Block\Product\ListProduct */
/** @var $escaper \Magento\Framework\Escaper  */
/** @var $viewModel \M2Commerce\CallForPrice\ViewModel\ProductView  */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$viewModel = $block->getData('viewModel');
?>

<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    if (empty($pos)) {
        $pos = 1;
    } ?>

    <div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image?>
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                           class="product photo product-item-photo"
                           tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php $productData = $viewModel->getProductData($_product); ?>
                            <?= $block->getProductPrice($_product) ?>

                            <?php if ($_product->isAvailable()) :?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php endif; ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $escaper->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($productData->getData('call_for_price') == 1):?>
                                        <div class="actions-primary call-for-price-action">
                                            <a href="javascript:void(0)" class="action primary call-for-price" data-product-id="<?= $_product->getEntityId(); ?>"><?= __('Call For Price') ?></a>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($productData->getData('call_for_price') == 0): ?>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $escaper->escapeHtmlAttr($position) : '' ?>>
                                            <?php if ($_product->isSaleable()) :?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $escaper->escapeHtmlAttr($_product->getSku()) ?>"
                                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                      method="post">
                                                    <input type="hidden"
                                                           name="product"
                                                           value="<?= $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= $postParams['data'][ActionInterface::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else :?>
                                                <?php if ($_product->isAvailable()) :?>
                                                    <div class="stock available"><span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else :?>
                                                    <div class="stock unavailable"><span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>

                                        <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $escaper->escapeHtmlAttr($position) : '' ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>

                                <?php if ($showDescription) :?>
                                    <div class="product description product-item-description">
                                        <?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                           title="<?= $_productNameStripped ?>"
                                           class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>

    <!-- Call for price modal start -->
    <div class="call-for-price-modal">
        <div class="alert-success" role="alert">
            <?= __('Your request has been sent successfully!')?>
        </div>
        <label class="label" for="req_name">
            <span><?= __('Name')?></span>
            <span class="mandatory-field"> *</span>
        </label>
        <input name="name" id="req_name" title="req_name" class="input-text" type="text"/>
        <div class="modal-error name-error">
            <span class="modal-error-msg"><?= __('Name is required')?></span>
        </div>
        <label class="label" for="req_email">
            <span><?= __('Email')?></span>
            <span class="mandatory-field"> *</span>
        </label>
        <input name="req_email" id="req_email" title="req_email" class="input-text" type="email"/>
        <div class="modal-error email-error">
            <span class="modal-error-msg"><?= __('Email is required')?></span>
        </div>
        <div class="modalemail-error">
            <span class="modal-error-msg"><?= __('Provide a valid email')?></span></div>
        <label class="label" for="req_phone">
            <span>Phone</span>
            <span class="mandatory-field"> *</span>
        </label>
        <input name="phone" id="req_phone" title="req_phone" class="input-text" type="text"/>
        <div class="modal-error phone-error">
            <span class="modal-error-msg"><?= __('Phone is required')?></span>
        </div>
        <input name="product_id" id="product_id" title="product_id" class="input-text" type="text" hidden/>
    </div>
    <!-- Call for price modal end -->

    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "M2Commerce_CallForPrice/js/call-for-price-modal" : {}
            }
        }
    </script>
<?php endif; ?>
