<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_CallForPrice
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

use Magento\Catalog\Model\Product;
use Magento\Swatches\Block\Product\Renderer\Listing\Configurable;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

/** @var Configurable $block */
/** @var Product $product */
/** @var $copViewModel \M2Commerce\CallForPrice\ViewModel\ProductView  */

$product = $block->getProduct();
$copViewModel = $block->getData('callForPriceViewModel');
$productData = $copViewModel->getProductData($product);
?>
<?php if ($productData->getData('call_for_price') == 0): ?>
    <?php if ($product && $product->isAvailable()): ?>
        <?php $productId = $product->getId() ?>
        <?php /** @var ConfigurableViewModel $configurableViewModel */ ?>
        <?php $configurableViewModel = $block->getConfigurableViewModel() ?>
        <div class="swatch-opt-<?= $block->escapeHtmlAttr($productId) ?>"
             data-role="swatch-option-<?= $block->escapeHtmlAttr($productId) ?>"></div>

        <script type="text/x-magento-init">
            {
                "[data-role=swatch-option-<?= $block->escapeJs($productId) ?>]": {
                    "Magento_Swatches/js/swatch-renderer": {
                        "selectorProduct": ".product-item-details",
                        "onlySwatches": true,
                        "enableControlLabel": false,
                        "numberToShow": <?=  $block->escapeJs($block->getNumberSwatchesPerProduct()) ?>,
                        "jsonConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                        "jsonSwatchConfig": <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>,
                        "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                        "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                        "showTooltip": <?= $block->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>
                    }
                }
            }
        </script>

        <script type="text/x-magento-init">
            {
                "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeJs($productId) ?>]": {
                    "priceBox": {
                        "priceConfig": {
                            "priceFormat": <?= /* @noEscape */ $block->getPriceFormatJson() ?>,
                            "prices": <?= /* @noEscape */ $block->getPricesJson() ?>
                        }
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
