<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_CallForPrice
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $_product = $block->getProduct(); ?>

<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()):
    if ($_product->getCallForPrice() == 0): ?>
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()) : ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?= $escaper->escapeHtml(__('Qty')) ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   min="0"
                                   value="<?= $block->getProductDefaultQty() * 1 ?>"
                                   title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty"
                                   data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                        </div>
                    </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?= $escaper->escapeHtmlAttr($buttonTitle) ?>"
                            class="action primary tocart"
                            id="product-addtocart-button" disabled>
                        <span>Add to Cart</span>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>

        <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "Magento_Catalog/js/validate-product": {}
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
