<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_CallForPrice
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/** @var $block Magento\Catalog\Block\Product\View */

$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . $block->escapeHtmlAttr(__('* Required Fields')) . '"';
}
?>
<?php $_product = $block->getProduct(); ?>
<?php if ($_product->getCallForPrice() == 0):?>
    <div class="product-options-wrapper" id="product-options-wrapper"<?= /* @noEscape */ $required ?>>
        <div class="fieldset" tabindex="0">
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
<?php endif; ?>
